apiVersion: v1
kind: Service
metadata:
  name: mavenapp
spec:
  type: NodePort
  ports:
  - port: 80          # Port exposed within the cluster
    targetPort: 6379 # Port on the pods
    nodePort: 30000   # Port accessible externally on each node
  selector:
    app: example-app  # Select pods with this label
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deployment
  labels:
    app: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: mavenapp
        image: us-central1-docker.pkg.dev/swift-terra-417207/ga/mavenapp
        ports:
        - containerPort: 80
